### ISSUE TITLE
Synchronize branches

### ISSUE THREAD

**Issue by minhnh** [b-it-bots/mas_perception_msgs#20]
I noticed there are several branches with conflicting changes for this repository (e.g. `noetic-devel` is behind `kinetic-devel`), which one is everyone using @alex-mitrevski @sthoduka @mhwasil @deebuls? Maybe we should synchronize this to `noetic` & `noetic-devel`?

**Comment by sthoduka** [comment]
Yes, I don't think there are conflicting changes though; maybe just one diverging commit. mas_industrial is using `noetic`, which looks like it's the same as `kinetic-devel` except for one commit. `noetic-devel` was some way behind and had one commit of its own.
I think #21 and #22 should fix it?

**Comment by minhnh** [comment]
The PRs look good to me, maybe @alex-mitrevski wants to take a look to make sure that there are no unexpected changes.

**Comment by alex-mitrevski** [comment]
Merged the PRs. I'll close this issue now.
